# Site settings
exclude: [README.md,example1.md,example2.md]
title: Omar Chehab
email: l-emir-omar.chehab@inria.fr
github: l-omar-chehab
twitter: lomarchehab
scholar_id: P0nFnfAAAAAJ
description: > # this symbol means ignore newlines until "baseurl:"
    Here you will find details about my work.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://l-omar-chehab.github.io" # the base hostname & protocol for your site
#paginate: 3



# Build settings
markdown: kramdown
